HydrusSharp/Controllers/ClientController.cs
using HydrusSharp.Data.Models.Client;
using HydrusSharp.Data.Models.ClientMappings;
using HydrusSharp.Data.Models.ViewModels;
using HydrusSharp.Data.Repositories;
using HydrusSharp.Data.Repositories.DataAccess;
using HydrusSharp.Services;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace HydrusSharp.Controllers
{
    public class ClientController : Controller
    {
        public ClientController()
        {
        }

        [HttpGet]
        [ActionName("JsonDumps")]
        public JsonResult GetJsonDumps()
        {
            IJsonDumpRepository jsonDumpRepository = new DAJsonDumpRepository();
            IEnumerable<JsonDump> jsonDumps = jsonDumpRepository.GetJsonDumps();

            return Json(ResultViewModel.Success(jsonDumps), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [ActionName("Sessions")]
        public JsonResult GetSessions()
        {
            IJsonDumpRepository jsonDumpRepository = new DAJsonDumpRepository();
            IEnumerable<NamedJsonDump> sessions = jsonDumpRepository.GetSessions();

            return Json(ResultViewModel.Success(sessions), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [ActionName("HashedJsonDumps")]
        public JsonResult GetHashedJsonDumps()
        {
            IJsonDumpRepository jsonDumpRepository = new DAJsonDumpRepository();
            IEnumerable<HashedJsonDump> jsonDump = jsonDumpRepository.GetHashedJsonDumps();

            return Json(ResultViewModel.Success(jsonDump), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [ActionName("HashedJsonDump")]
        public JsonResult GetHashedJsonDumps(string hash)
        {
            IJsonDumpRepository jsonDumpRepository = new DAJsonDumpRepository();
            HashedJsonDump jsonDump = jsonDumpRepository.GetHashedJsonDump(hash);

            return Json(ResultViewModel.Success(jsonDump), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ActionName("MatchingFileInfo")]
        public JsonResult GetMatchingFileInfo(MediaCollectViewModel collect, MediaSortViewModel sort, SearchPredicateViewModel[] filters, int skip, int take)
        {
            IFileRepository fileRepository = new DAFileRepository();
            IMappingRepository mappingRepository = new DAMappingRepository();
            ITagRepository tagRepository = new DATagRepository();

            IEnumerable<CurrentMapping> matchingMappings = mappingRepository.GetMatchingMappings(collect, sort, filters, skip, take);
            IEnumerable<FileInfo> fileInfos = fileRepository.GetFileInfos(matchingMappings.Select(mapping => mapping.HashId));
            int totalCount = mappingRepository.GetMappingsCount(collect, filters);

            PaginatedResultViewModel paginatedResults = new PaginatedResultViewModel
            {
                Count = totalCount,
                Items = fileInfos.Select(fileInfo => new FileInfoViewModel
                {
                    HashId = fileInfo.HashId,
                    Size = fileInfo.Size,
                    Width = fileInfo.Width ?? 0,
                    Height = fileInfo.Height ?? 0,
                    MimeType = fileInfo.MimeType.ToString(),
                    Duration = fileInfo.Duration,
                    FrameCount = fileInfo.FrameCount,
                    HasAudio = fileInfo.HasAudio,
                    Tags = matchingMappings.First(mapping => mapping.HashId == fileInfo.HashId).Tags.ToArray()
                })
                .ToArray()
            };

            return Json(ResultViewModel.Success(paginatedResults));
        }

        [HttpGet]
        [ActionName("Option")]
        public JsonResult GetOption(string optionName)
        {
            IOptionRepository optionRepository = new DAOptionRepository();
            OptionCollection optionCollection = optionRepository.GetOptions();
            OptionService optionService = new OptionService();

            string value = optionService.GetValue(optionCollection, optionName);

            return Json(ResultViewModel.Success(value), JsonRequestBehavior.AllowGet);
        }
    }
}

HydrusSharp/Controllers/HomeController.cs
using System.Web.Mvc;

namespace HydrusSharp.Controllers
{
    public class HomeController : Controller
    {
        public HomeController()
        {
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
    }
}

HydrusSharp/Controllers/MediaController.cs
using HydrusSharp.Core.Enums;
using HydrusSharp.Data.Models.ClientMaster;
using HydrusSharp.Data.Repositories;
using HydrusSharp.Data.Repositories.DataAccess;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace HydrusSharp.Controllers
{
    public class MediaController : Controller
    {
        public MediaController()
        {
        }

        [HttpGet]
        public ActionResult GetMedia(int hashId, bool isThumbnail)
        {
            IHashRepository hashRepository = new DAHashRepository();
            Hash matchingHash = hashRepository.GetById(hashId);

            DirectoryInfo clientFilesDirectory = new DirectoryInfo(Path.Combine(ConfigurationManager.AppSettings["HydrusNetworkDB"], "client_files"));
            if (!clientFilesDirectory.Exists)
            {
                throw new InvalidOperationException("Could not find the client files directory");
            }

            IEnumerable<DirectoryInfo> subdirectories = clientFilesDirectory.EnumerateDirectories();
            IEnumerable<FileInfo> files = clientFilesDirectory.EnumerateFiles("*", SearchOption.AllDirectories);
            IEnumerable<FileInfo> matchingMedias = files.Where(media => media.Name.Substring(0, media.Name.Length - media.Extension.Length) == matchingHash.HashString);
            FileInfo matchingMedia = matchingMedias.FirstOrDefault(media => (media.Extension == ".thumbnail") == isThumbnail);


            if (matchingMedia == null)
            {
                return new HttpStatusCodeResult(404, "Media item not found");
            }

            IFileRepository fileRepository = new DAFileRepository();
            MimeType mimeType = fileRepository.GetMimeType(hashId);

            IMappingRepository mappingRepository = new DAMappingRepository();

            // Downloads the file instead of setting the tab title. Leave as-is for now
            //string title = mappingRepository.GetFileTitle(hashId) ?? $"Media (Hash {hashId})";

            IDictionary<MimeType, string> mimeToContentTypes = new Dictionary<MimeType, string>
            {
                { MimeType.IMAGE_APNG, "image/apng" },
                { MimeType.IMAGE_BMP, "image/bmp" },
                { MimeType.IMAGE_GIF, "image/gif" },
                { MimeType.IMAGE_ICON, "image/vnd.microsoft.icon" },
                { MimeType.IMAGE_JPEG, "image/jpeg" },
                { MimeType.IMAGE_PNG, "image/png" },
                { MimeType.IMAGE_SVG, "image/svg+xml" },
                { MimeType.IMAGE_TIFF, "image/tiff" },
                { MimeType.IMAGE_WEBP, "image/webp" },
                { MimeType.UNDETERMINED_PNG, "image/png" },
                { MimeType.GENERAL_IMAGE, "image/jpeg" },
                { MimeType.VIDEO_AVI, "video/x-msvideo" },
                { MimeType.VIDEO_FLV, "video/x-flv" },
                { MimeType.VIDEO_MKV, "video/x-matroska" },
                { MimeType.VIDEO_MOV, "video/quicktime" },
                { MimeType.VIDEO_MP4, "video/mp4" },
                { MimeType.VIDEO_OGV, "video/ogg" },
                { MimeType.VIDEO_REALMEDIA, "application/vnd.rn-realmedia" },
                { MimeType.VIDEO_WEBM, "video/webm" },
                { MimeType.VIDEO_WMV, "video/x-ms-wmv" },
                { MimeType.GENERAL_VIDEO, "video/mp4" },
                { MimeType.UNDETERMINED_MP4, "video/mp4" }
            };

            string contentType = mimeToContentTypes[mimeType] ?? "octet/stream";

            return new FileStreamResult(matchingMedia.OpenRead(), contentType);
            //{
            //    FileDownloadName = title
            //};
        }
    }
}

HydrusSharp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<input type="hidden" data-url="Client,Sessions" value="@Url.Action("Sessions", "Client")" />
<input type="hidden" data-url="Client,HashedJsonDump" value="@Url.Action("HashedJsonDump", "Client")" />
<input type="hidden" data-url="Client,Option" value="@Url.Action("Option", "Client")" />
<input type="hidden" data-url="Client,MatchingFileInfo" value="@Url.Action("MatchingFileInfo", "Client")" />

<main>
    <section>
        <div class="row">
            <!-- Session selector -->
            <div class="col-sm-3">
                <div class="input-group">
                    <label class="input-group-text" for="ddb_Sessions">Session</label>
                    <select class="form-select" data-bind="options: sessions, optionsText: (session) => `${session.name()}`, value: currentSession"></select>
                </div>
            </div>
            <!-- Session information -->
            <div class="col-sm-9" data-bind="visible: hashedJsonDump() !== null, with: hashedJsonDump()">
                <ul class="list-group list-group-horizontal" data-bind="with: managementController">
                    <li class="list-group-item" style="padding: 6px 16px">
                        <strong data-bind="text: name"></strong>
                    </li>
                    <li class="list-group-item" data-bind="with: mediaSort" style="padding: 6px 16px">
                        Order by
                        <span data-bind="visible: sortBy() !== 'system', text: '\'' + namespaces().join('-') + '\''"></span>
                        <span data-bind="visible: sortBy() === 'system', text: '\'' + friendlySystemSortType() + '\''"></span>
                        in
                        <span data-bind="text: ascending() ? 'ASC' : 'DESC'"></span>
                        order
                    </li>
                    <li class="list-group-item" data-bind="with: mediaCollect, visible: mediaCollect().namespaces().length !== 0" style="padding: 6px 16px">
                        Collect by
                        <span data-bind="text: namespaces().join('-')"></span>
                    </li>
                </ul>
            </div>
        </div>
    </section>
    <!-- Page selector -->
    <section data-bind="visible: currentSession() !== null, with: currentSession">
        <div data-bind="with: notebook">
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">HydrusSharp</a>
                    <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#Pages" aria-controls="Pages" aria-expanded="false" aria-label="Toggle pages">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div id="Pages" class="collapse navbar-collapse">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <!-- ko foreach: items -->
                            <li class="nav-item dropdown" data-bind="visible: serialisableType() === 106">
                                <button type="button" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" data-bind="text: name, attr: { id: name }"></button>
                                <div class="dropdown-menu">
                                    <!-- ko foreach: typeof(items) !== 'undefined' ? items : [] -->
                                    <button type="button" class="dropdown-item" data-bind="text: $data.name, click: () => { $root.loadHashedJsonDumpAsync($data.hash()); }"></button>
                                    <!-- /ko -->
                                </div>
                            </li>
                            <li class="nav-item" data-bind="visible: serialisableType() === 107">
                                <a href="#" class="nav-link" data-bind="text: name, click: () => { $root.loadHashedJsonDumpAsync($data.hash()); }"></a>
                            </li>
                            <!-- /ko -->
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </section>
    <!-- Sidebar -->
    <aside class="d-flex flex-column flex-shrink-0 bg-body-secondary sidebar" data-bind="visible: hashedJsonDump() !== null, with: hashedJsonDump()">
        <div data-bind="with: managementController().fileSearchContext">
            <ul class="list-group">
                <!-- ko foreach: predicates -->
                <li class="list-group-item">
                    <span data-bind="attr: { class: searchType() === 0 ? '' : 'fst-italic' }">
                        <span data-bind="visible: mustBeTrue() != true">-</span>
                        <span data-bind="text: friendlySearchType"></span>
                    </span>
                </li>
                <!-- /ko -->
            </ul>
        </div>
    </aside>
    <!-- Returned media -->
    <section class="d-flex flex-column flex-shrink-0 p-3 searchResults">
        <div data-bind="visible: loadingFiles() === false">
            <ol class="d-flex flex-row flex-wrap list-unstyled">
                <!-- ko foreach: fileInfos -->
                <li class="m-1" data-bind="attr: { style: `width: ${$root.thumbnailWidth()}px; margin-right: 10px` }">
                    <a class="figure img-thumbnail" target="_blank" data-bind="attr: { href: `@Url.Action("GetMedia", "Media")?hashId=${hashId()}&isThumbnail=false` }">
                        <div class="figure-img img-thumbnail border-0 d-flex flex-column justify-content-around overflow-hidden position-relative" data-bind="attr: { style: `width: ${$root.thumbnailWidth()}px; height: ${$root.thumbnailHeight()}px;` }">
                            <img class="flex-grow-0 text-center fs-1 lh-lg bg-danger-subtle" data-bind="attr: { srcset: `@Url.Action("GetMedia", "Media")?hashId=${hashId()}&isThumbnail=true` }" style="width: 100%" alt="Missing Item" />
                        </div>
                        <figcaption class="figure-caption text-center fw-bold" data-bind="text: tags().filter(tag => tag.namespace() === 'title').map(tag => tag.subTag()).join(', ')"></figcaption>
                    </a>
                </li>
                <!-- /ko -->
            </ol>
        </div>
        <div data-bind="visible: loadingFiles() === true">
            Loading...
        </div>
        <nav aria-label="Search result pages">
            <ol class="pagination">
                <li data-bind="visible: $root.numberOfPages() !== 0" class="page-item">
                    <a class="page-link" data-bind="text: 'First', click: () => { $root.selectedPage(1); }, attr: { href: 1 !== $root.selectedPage() ? '#' : null }"></a>
                </li>
                <!-- ko foreach: selectablePages -->
                <li data-bind="attr: { class: $data !== $root.selectedPage() ? 'page-item' : 'page-item active' }" class="page-item">
                    <a class="page-link" data-bind="text: $data, click: () => { $root.selectedPage($data); }, attr: { href: $data !== $root.selectedPage() ? '#' : null }"></a>
                </li>
                <!-- /ko -->
                <li data-bind="visible: $root.numberOfPages() !== 0" class="page-item">
                    <a class="page-link" data-bind="text: 'Last', click: () => { $root.selectedPage($root.numberOfPages()); }, attr: { href: $root.numberOfPages() !== $root.selectedPage() ? '#' : null }"></a>
                </li>
            </ol>
        </nav>
    </section>
</main>

@section scripts {

    @Scripts.Render("~/bundles/scripts/index")
}

HydrusSharp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    @Styles.Render("~/bundles/styles/common")
</head>
<body>
    @RenderBody()

    <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.5.0/knockout-min.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/@("@")popperjs/core@2" crossorigin="anonymous"></script>
    @Scripts.Render("~/scripts/bootstrap")
    @Scripts.Render("~/bundles/scripts/common")

    @RenderSection("scripts", required: false)
</body>
</html>